### ISSUE TITLE
Deal with phased genotyping data

### ISSUE THREAD

**Issue by olivierlabayle** [TARGENE/targene-pipeline#52]
Support is provided only for unphased genotypes at the moment.

This causes (undetectable) issues in the tests at the moment.

**Comment by olivierlabayle** [comment]
Support for phased data may be actually quite complex and not immedialtely of interest then:

- [ ] convert test data to unphased data 
- [ ] add a check in TarGene that the dataset is actually unphased

**Comment by kose-y** [comment]
Currently, the `first_allele_dosage!()` function in the BGEN package supports unphased data through the `first_dosage_phased!()` function (https://github.com/OpenMendel/BGEN.jl/blob/main/src/genotypes.jl#L366), and if some undesired behavior is happening, it might a bug in that function.
