### ISSUE TITLE
create flexible nextflow.config parameters

### ISSUE THREAD

**Issue by roskamsh** [TARGENE/targene-pipeline#56]
- compatible with non-UKBB cohorts
- objectives:
1. change UKBB_BED_FILES and UKBB_BGEN_FILES to just BED_FILES and BGEN_FILES
2. add COHORT
3. QC_FILE, TRAITS_CONFIG and WITHDRAWAL_LIST optional

**Comment by roskamsh** [comment]
Completed here: [052acb4]

**Comment by olivierlabayle** [comment]
closing as tracked by milestone
